name: OpenCADC MatPlotLib Docker CI

on:
  pull_request:
  push:
  release:

jobs:
  #
  # Package jobs
  #
  package-3_12:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      name: matplotlib
      version: '3.12'
      flavour: slim
  package-3_13:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      name: matplotlib
      version: '3.13'
      flavour: slim
#
# End Package Jobs
#
